import { HealthCategory, Issue, WardRisk } from "./types";

export const issues: Issue[] = [
  {
    id: "1041",
    title: "Open Manhole",
    category: "Open Manhole",
    description: "Uncovered manhole near the City School main gate. High pedestrian activity, risk of injury.",
    ward: "Ward 12",
    lat: 22.7196,
    lng: 75.8577,
    x: 24,
    y: 32,
    severity: "critical",
    severityScore: 91,
    severityFactors: [
      { label: "Damage size", score: 32, max: 35 },
      { label: "Road importance", score: 25, max: 25 },
      { label: "Traffic exposure", score: 18, max: 20 },
      { label: "Nearby school", score: 10, max: 10 },
      { label: "Historical incidents", score: 6, max: 10 },
    ],
    priorityScore: 98,
    priorityFactors: [
      { label: "Severity", score: 30, max: 30 },
      { label: "Traffic exposure", score: 20, max: 20 },
      { label: "Near school", score: 15, max: 15 },
      { label: "Reports merged", score: 14, max: 15 },
      { label: "Road importance", score: 10, max: 10 },
      { label: "Age of complaint", score: 9, max: 10 },
    ],
    confidence: 96,
    status: "assigned",
    department: "Roads",
    duplicateCount: 4,
    reportedAt: "2 days ago",
    imageDescription: "Open manhole on a paved road beside a school boundary wall.",
  },
  {
    id: "1039",
    title: "Major Pothole",
    category: "Pothole",
    description: "Large, deep pothole on the main highway carriageway. Multiple two-wheeler riders reported near-misses.",
    ward: "Ward 3",
    lat: 22.7096,
    lng: 75.8677,
    x: 62,
    y: 55,
    severity: "critical",
    severityScore: 94,
    severityFactors: [
      { label: "Damage size", score: 34, max: 35 },
      { label: "Road importance", score: 25, max: 25 },
      { label: "Traffic exposure", score: 19, max: 20 },
      { label: "Nearby school", score: 6, max: 10 },
      { label: "Historical incidents", score: 10, max: 10 },
    ],
    priorityScore: 94,
    priorityFactors: [
      { label: "Severity", score: 29, max: 30 },
      { label: "Traffic exposure", score: 20, max: 20 },
      { label: "Near school", score: 4, max: 15 },
      { label: "Reports merged", score: 15, max: 15 },
      { label: "Road importance", score: 10, max: 10 },
      { label: "Age of complaint", score: 8, max: 10 },
    ],
    confidence: 94,
    status: "in_progress",
    department: "Roads",
    duplicateCount: 7,
    reportedAt: "1 day ago",
    imageDescription: "Deep pothole spanning half the lane width on Highway 6.",
  },
  {
    id: "1044",
    title: "Broken Traffic Signal",
    category: "Traffic Signal",
    description: "Signal stuck on red for all directions at Junction 5, causing congestion during peak hours.",
    ward: "Ward 7",
    lat: 22.7296,
    lng: 75.8477,
    x: 44,
    y: 22,
    severity: "critical",
    severityScore: 88,
    severityFactors: [
      { label: "Damage size", score: 22, max: 35 },
      { label: "Road importance", score: 24, max: 25 },
      { label: "Traffic exposure", score: 20, max: 20 },
      { label: "Nearby school", score: 4, max: 10 },
      { label: "Historical incidents", score: 8, max: 10 },
    ],
    priorityScore: 92,
    priorityFactors: [
      { label: "Severity", score: 27, max: 30 },
      { label: "Traffic exposure", score: 20, max: 20 },
      { label: "Near school", score: 3, max: 15 },
      { label: "Reports merged", score: 13, max: 15 },
      { label: "Road importance", score: 10, max: 10 },
      { label: "Age of complaint", score: 7, max: 10 },
    ],
    confidence: 91,
    status: "reported",
    department: "Electrical",
    duplicateCount: 2,
    reportedAt: "5 hours ago",
    imageDescription: "Traffic signal box at a busy four-way junction.",
  },
  {
    id: "1050",
    title: "Streetlight Outage",
    category: "Streetlight",
    description: "Row of three streetlights not functioning along Park Row, dark stretch at night.",
    ward: "Ward 9",
    lat: 22.7396,
    lng: 75.8377,
    x: 78,
    y: 40,
    severity: "medium",
    severityScore: 67,
    severityFactors: [
      { label: "Damage size", score: 20, max: 35 },
      { label: "Road importance", score: 16, max: 25 },
      { label: "Traffic exposure", score: 12, max: 20 },
      { label: "Nearby school", score: 4, max: 10 },
      { label: "Historical incidents", score: 5, max: 10 },
    ],
    priorityScore: 67,
    priorityFactors: [
      { label: "Severity", score: 20, max: 30 },
      { label: "Traffic exposure", score: 12, max: 20 },
      { label: "Near school", score: 2, max: 15 },
      { label: "Reports merged", score: 6, max: 15 },
      { label: "Road importance", score: 7, max: 10 },
      { label: "Age of complaint", score: 5, max: 10 },
    ],
    confidence: 89,
    status: "reported",
    department: "Electrical",
    duplicateCount: 1,
    reportedAt: "3 days ago",
    imageDescription: "Dark stretch of road with an unlit streetlight pole.",
  },
  {
    id: "1052",
    title: "Minor Road Crack",
    category: "Road Crack",
    description: "Surface cracking along a residential lane, not yet affecting vehicle movement.",
    ward: "Ward 2",
    lat: 22.6996,
    lng: 75.8777,
    x: 30,
    y: 70,
    severity: "low",
    severityScore: 38,
    severityFactors: [
      { label: "Damage size", score: 10, max: 35 },
      { label: "Road importance", score: 8, max: 25 },
      { label: "Traffic exposure", score: 8, max: 20 },
      { label: "Nearby school", score: 2, max: 10 },
      { label: "Historical incidents", score: 3, max: 10 },
    ],
    priorityScore: 38,
    priorityFactors: [
      { label: "Severity", score: 10, max: 30 },
      { label: "Traffic exposure", score: 8, max: 20 },
      { label: "Near school", score: 1, max: 15 },
      { label: "Reports merged", score: 3, max: 15 },
      { label: "Road importance", score: 4, max: 10 },
      { label: "Age of complaint", score: 3, max: 10 },
    ],
    confidence: 82,
    status: "resolved",
    department: "Roads",
    duplicateCount: 1,
    reportedAt: "9 days ago",
    imageDescription: "Hairline cracking on a residential lane surface.",
  },
  {
    id: "1027",
    title: "Garbage Accumulation",
    category: "Garbage",
    description: "Uncollected garbage pile near the Ward 9 community bin, reported by several residents.",
    ward: "Ward 9",
    lat: 22.7146,
    lng: 75.8627,
    x: 85,
    y: 62,
    severity: "medium",
    severityScore: 58,
    severityFactors: [
      { label: "Damage size", score: 16, max: 35 },
      { label: "Road importance", score: 10, max: 25 },
      { label: "Traffic exposure", score: 8, max: 20 },
      { label: "Nearby school", score: 6, max: 10 },
      { label: "Historical incidents", score: 8, max: 10 },
    ],
    priorityScore: 58,
    priorityFactors: [
      { label: "Severity", score: 17, max: 30 },
      { label: "Traffic exposure", score: 8, max: 20 },
      { label: "Near school", score: 6, max: 15 },
      { label: "Reports merged", score: 9, max: 15 },
      { label: "Road importance", score: 5, max: 10 },
      { label: "Age of complaint", score: 4, max: 10 },
    ],
    confidence: 90,
    status: "resolved",
    department: "Sanitation",
    duplicateCount: 3,
    reportedAt: "6 days ago",
    imageDescription: "Overflowing community garbage bin on a street corner.",
  },
];

export const wardRisks: WardRisk[] = [
  {
    ward: "Ward 12",
    category: "Road damage",
    risk: 82,
    window: "Next 30 days",
    reasons: [
      "28% increase in complaints over 8 weeks",
      "Heavy daily traffic load",
      "Previous road repairs in the same stretch",
      "Recent rainfall in the area",
    ],
    recommendedActions: [
      "Inspect Ward 12 roads this week",
      "Prioritise resurfacing on Highway 6",
      "Schedule preventive maintenance",
    ],
  },
  {
    ward: "Ward 4",
    category: "Waterlogging",
    risk: 67,
    window: "Next 30 days",
    reasons: [
      "Low-lying drainage zone",
      "Repeated waterlogging in past monsoons",
      "Drainage complaints up 19% this quarter",
    ],
    recommendedActions: [
      "Inspect drainage near Sector 4",
      "Clear blocked stormwater lines before monsoon",
    ],
  },
  {
    ward: "Ward 9",
    category: "Garbage overflow",
    risk: 54,
    window: "Next 30 days",
    reasons: [
      "Bin collection frequency below target",
      "Population density above ward average",
    ],
    recommendedActions: [
      "Increase collection frequency in Ward 9",
      "Add a secondary community bin",
    ],
  },
  {
    ward: "Ward 2",
    category: "Streetlight failure",
    risk: 31,
    window: "Next 30 days",
    reasons: ["Ageing fixtures beyond expected service life"],
    recommendedActions: ["Schedule routine fixture inspection"],
  },
];

export const healthCategories: HealthCategory[] = [
  { label: "Roads", score: 68 },
  { label: "Streetlights", score: 82 },
  { label: "Water", score: 71 },
  { label: "Sanitation", score: 79 },
  { label: "Traffic", score: 83 },
];

export const cityHealthScore = Math.round(
  healthCategories.reduce((a, c) => a + c.score, 0) / healthCategories.length
);

export const demoStats = {
  totalReports: 2481,
  duplicateReports: 731,
  criticalIssues: 186,
  hotspots: 42,
};

export const trendSeries = [
  { week: "W1", reports: 120 },
  { week: "W2", reports: 142 },
  { week: "W3", reports: 131 },
  { week: "W4", reports: 168 },
  { week: "W5", reports: 159 },
  { week: "W6", reports: 190 },
  { week: "W7", reports: 176 },
  { week: "W8", reports: 205 },
  { week: "W9", reports: 198 },
  { week: "W10", reports: 224 },
  { week: "W11", reports: 211 },
  { week: "W12", reports: 238 },
];

export const categorySeries = [
  { name: "Pothole", value: 640, color: "var(--critical)" },
  { name: "Streetlight", value: 410, color: "var(--high)" },
  { name: "Garbage", value: 505, color: "#6FA8B5" },
  { name: "Water leak", value: 260, color: "var(--low)" },
  { name: "Signal", value: 180, color: "#9B8F73" },
  { name: "Other", value: 320, color: "#B58562" },
];

export function getIssue(id: string) {
  return issues.find((i) => i.id === id);
}
